# source "%val{config}/plugins/plug.kak/rc/plug.kak"

# plug "alexherbo2/auto-pairs.kak"
# plug "https://github.com/h-youhei/kakoune-close-tag"
map global insert <c-ret> '<esc>:close-tag<ret>i'
# plug "andreyorst/powerline.kak" defer "powerline" %{
# hook global ModuleLoaded "powerline" * %{
       # powerline-theme base16-gruvbox
# }
# }
# plug "andreyorst/fzf.kak" defer "fzf" %{
#     set-option global fzf_implementation 'sk'
#     set-option global fzf_file_command 'rg'
#     map global normal <c-p> ': fzf-mode<ret>'
# }
# plug "ul/kak-lsp" do %{
#       cargo install --locked --force --path .
# } config %{
#   define-command lsp-restart %{ lsp-stop; lsp-start }
#   set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"
#   set-option global lsp_diagnostic_line_error_sign "!"
#   set-option global lsp_diagnostic_line_warning_sign "?"
#   hook global WinSetOption filetype=(ruby) %{
#     map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
#     lsp-enable-window
#     lsp-auto-hover-enable
#     lsp-auto-hover-insert-mode-disable
#     set-option window lsp_hover_anchor true
#     set-face window DiagnosticError default+u
#     set-face window DiagnosticWarning default+u
#   }
#   hook global KakEnd .* lsp-exit
# }

hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

# map global normal <space> , -docstring 'leader'
# conflicts with consolidate selections

# tab/indentation stuff
hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 2
set global indentwidth 2                                                    
addhl global/ wrap
map global normal = '|fmt -w $kak_opt_autowrap_column<ret>'

hook global InsertCompletionShow .* %{
  try %{
    # this command temporarily removes cursors preceded by whitespace;
    # if there are no cursors left, it raises an error, does not
    # continue to execute the mapping commands, and the error is eaten
    # by the `try` command so no warning appears.
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
  }
}

hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

colorscheme gruvbox
set-face global comment rgb:8a8885

add-highlighter global/ number-lines -relative
add-highlighter global/ show-matching

# write buffers on lose focus?
hook global FocusOut .* %{ echo -debug focus out }

map global user 'c' ': comment-line<ret>' -docstring 'comment selection'

hook global WinSetOption filetype=html %{
  set window formatcmd 'reshape'
}

hook global WinSetOption filetype=javascript %{
  set buffer lintcmd './node_modules/.bin/eslint --format=node_modules/eslint-formatter-kakoune -c .eslintrc'
  lint-enable
  lint
}

hook global WinSetOption filetype=scss %{
  set buffer lintcmd 'stylelint "**/*.scss"'
  lint-enable
  lint
}
